services:
  - type: web
    name: peticiones-backend
    runtime: python
    plan: free
    repo: https://github.com/DaveLedriv/peticiones-ciudadanas
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: peticiones-db
          property: connectionString

databases:
  - name: peticiones-db
    plan: free
